Add flag to force clear solr even if not enabled.
4teamwork/ftw.solr pull request #184
Opened 2021-09-17 06:54 UTC by njohner

This is used when wiping and setting up Gever again.

2021-09-20 14:49 UTC, lukasgraf requested changes
LGTM 👍 
But changelog is missing, which would be an issue when trying to release `ftw.solr`, even though it's a trivial change.

2021-09-20 15:37 UTC, njohner commented
Yep right thanks. I think this would still be a MINOR release right?

2021-09-21 06:04 UTC, lukasgraf approved these changes

2021-09-21 06:05 UTC, merged

2021-09-21 06:05 UTC, lukasgraf commented
Yes, I'd say minor.